In [3]:

serialStr = '/dev/cu.usbmodem14111'
charList = list(serialStr)
charList[-2] = '1' if charList[-2] == '3' else '3'
targetPort = "".join(charList)

print(targetPort)


/dev/cu.usbmodem14131


In [4]:

import numpy as np



In [23]:


test = np.zeros((20, 5))

test.shape


(20, 5)

In [9]:
test[-1][0] = 2

In [10]:
test

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0.]])

In [11]:
str1 = "hi"
a = 32
print(str1+" {}".format(a))


hi 32


In [24]:


for i in range(5):
    test[0][i] = i

test


array([[0., 1., 2., 3., 4.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.sum(test, axis=0)

array([2., 1., 2., 3., 4.])

In [15]:
print("hi {}".format(3+4))

hi 7


In [21]:

test = test[0]
np.sum(test[np.where(test>2)])


7.0

In [17]:
testNew

array([3., 4.])

In [18]:
np.sum(test[np.where(test>2)], axis=0)

7.0

In [27]:
import pandas as pd

In [30]:

df = pd.DataFrame({'a': [1, 2, 3], 'b':[4,5,6]})
df[df.a > 1].sum()['b']   


11

In [31]:
import difflib

In [33]:

def diff(a, b):
    for i,s in enumerate(difflib.ndiff(a, b)):
        if s[0]==' ': continue
        elif s[0]=='-':
            print(u'Delete "{}" from position {}'.format(s[-1],i))
        elif s[0]=='+':
            print(u'Add "{}" to position {}'.format(s[-1],i))    
    print()      

In [34]:

a="BurgosMillie		@susan soltero #TodossomosSusan.......y recuerda que nadie le tira piedras a un árbol que no da frutos.......Bendecida"
b="BurgosMillie	@susan soltero #TodossomosSusan.......y recuerda que nadie le tira piedras a un árbol que no da frutos.......Bendecida"

diff(a,b)


()


In [36]:
import datetime

In [41]:

def diffTime(a, b):
    
    a = datetime.datetime.strptime(timeStr1, "%Y-%m-%d %H:%M:%S.%f")
    b = datetime.datetime.strptime(timeStr2, "%Y-%m-%d %H:%M:%S.%f")

    print((b-a).total_seconds())
    

In [42]:

timeStr1 = "2018-11-02 13:20:18.231240"
timeStr2 = "2018-11-02 13:21:28.964919"
diffTime(timeStr1, timeStr2)


70.733679
